name = "panda-closet-worker"
main = "worker/src/index.js"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "panda-closet"
database_id = "96af9d4d-0e8a-4af9-b4c8-06ec01605d93"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "panda-closet-images"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true
